### ISSUE TITLE
Expose api for programmatic use

### ISSUE THREAD

**Issue by erezmus** [libero/migrator#7]
Its currently difficult to use the package in a non cli form. For example, when running integration tests that need to migrate database as part of setup process, one needs to instantiate the `Cli` class to run a command. The problem is that it makes the process hang. This is something to do with how the `yargs` package works (this is overcome by using a process.exit(0), but we can't do this in a test).

Ideally, it would be great if we could import an underlying class (e.g. the Command one), so that it can be configured and used in a programmatic fashion.

**Comment by Cooryd** [comment]
Archiving repo
